### ISSUE TITLE
系统找不到指定路径

### ISSUE THREAD

**Issue by Ksuserkqy** [ChinaIceF/PyQt-SiliconUI#110]
```Traceback (most recent call last):
  File "e:\Desktop\PyQt-SiliconUI-main\examples\Gallery for siui\start.py", line 7, in <module>
    from siui.core.globals import SiGlobal
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\__init__.py", line 4, in <module>
    import siui.components as components
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\components\__init__.py", line 1, in <module>
    from siui.components.option_card import *
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\components\option_card\__init__.py", line 1, in <module>  
    from siui.components.option_card.option_card import *
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\components\option_card\option_card.py", line 3, in <module>
    from siui.components.option_card.abstracts.option_card import ABCSiOptionCardPlane
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\components\option_card\abstracts\__init__.py", line 1, in <module>
    from siui.components.option_card.abstracts.option_card import ABCSiOptionCardPlane
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\components\option_card\abstracts\option_card.py", line 1, in <module>
    from siui.components.widgets import SiDenseHContainer, SiDenseVContainer, SiLabel
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\components\widgets\__init__.py", line 1, in <module>      
    import siui.components.widgets.abstracts as abstarcts
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\components\widgets\abstracts\__init__.py", line 2, in <module>
    from siui.components.widgets.abstracts.button import *
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\components\widgets\abstracts\button.py", line 7, in <module>
    from siui.components.widgets.abstracts.widget import SiWidget
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\components\widgets\abstracts\widget.py", line 9, in <module>
    from siui.core.globals import SiGlobal
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\core\globals\__init__.py", line 1, in <module>
    from siui.core.globals.globals import SiGlobal
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\core\globals\globals.py", line 9, in <module>
    class SiliconUIGlobal:
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\core\globals\globals.py", line 24, in SiliconUIGlobal     
    iconpack = SiGlobalIconPack()
               ^^^^^^^^^^^^^^^^^^
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\gui\icons\parser.py", line 19, in __init__
    self.reload_internals()
  File "D:\appFoundation\Python\Python312\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\gui\icons\parser.py", line 25, in reload_internals
    for package_filename in os.listdir(self.package_folder_path):
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\appFoundation\\Python\\Python312\\Lib\\site-packages\\pyqt_siliconui-1.0.1-py3.12.egg\\siui\\gui\\icons\\packages'```

**Comment by ChinaIceF** [comment]
## 需要补充信息
您好，是否方便提供一下你的运行环境，下载库的时间，以及`D:\\appFoundation\\Python\\Python312\\Lib\\site-packages\\pyqt_siliconui-1.0.1-py3.12.egg\\siui\\gui\\icons\\`下的目录结构，以便我查找问题的原因

**Comment by Ksuserkqy** [comment]
Windows11 专业工作站版 23H2
![image](https://github.com/user-attachments/assets/2e5d6ccd-52aa-42d7-9b0b-eaf68384f1a7)
![image](https://github.com/user-attachments/assets/f825c178-db6a-4b3a-8f93-74bc54d043b1)
![image](https://github.com/user-attachments/assets/56ad3ce2-6234-401f-a13d-8408dfebf7d5)

**Comment by ChinaIceF** [comment]
## 问题已复现

## 原因和解决办法
`start.py`中未明确包含图标库文件(文件名形如`*.icons`)，你可以将仓库中`./siui/gui/icons/packages/`下的图标库文件复制到安装的目录下暂时解决这个问题，等下我改一下`setup.py`

**Comment by Ksuserkqy** [comment]
问题已解决，谢谢
同时我在执行start.py的时候程序说明我没有安装pyperclip第三方库，需要我自己手动安装，也许是setup.py里漏写了？希望这个对你有用

**Comment by ChinaIceF** [comment]
是的，刚刚安装的时候注意到了这个问题，因为一直用的编辑器运行所以没注意到这些细节问题，将会在一会一并修复，感谢
