### ISSUE TITLE
\examples\TODO list\ui.py 中 from siui.core.color import Color 问题

### ISSUE THREAD

**Issue by Can1425** [ChinaIceF/PyQt-SiliconUI#128]
我不知道这是否是我的问题，但的确这个问题出现了
详细的输出如下：
```
PS E:\Can1425\PyQt-SiliconUI\examples\TODO-list> E:/Can1425/Python/python.exe start.py
已将环境变量 QT_SCALE_FACTOR 设为 1.25  (来源: Windows API)
Traceback (most recent call last):
  File "E:\Can1425\PyQt-SiliconUI\examples\TODO-list\start.py", line 4, in <module>
    from ui import TODOApplication
  File "E:\Can1425\PyQt-SiliconUI\examples\TODO-list\ui.py", line 22, in <module>
    from siui.core.color import Color
ImportError: cannot import name 'Color' from 'siui.core.color' (E:\Can1425\Python\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\core\color\__init__.py). Did you mean: 'color'?
```
顺带说一句，这里为了方便开发，我将 TODO list 文件夹更名为了 TODO-list

**Comment by ChinaIceF** [comment]
这个工程里的 My-TODOs 应该是个遗留开发版本，这里导入的应该是`SiColor`类。
如果你想参考 My-TODOs，请在[其仓库](https://github.com/ChinaIceF/My-TODOs/)中下载正式版本的代码。

按理来说把`Color`改成`SiColor`可以正确导入，但由于版本不统一，仍然建议你使用 My-TODOs 中的代码。

**Comment by Can1425** [comment]
好的，感谢啦
