### ISSUE TITLE
[建议] 

### ISSUE THREAD

**Issue by HTT-Solaca** [ChinaIceF/PyQt-SiliconUI#132]
1.  选项卡 - 容器 中的 资源管理器 希望增加直接显示百分比的控件 本身的百分比条相对偏细 鼠标移上去会比较麻烦 
2. [文档] 希望开发者能够同步完成代码的使用文档 以便于二次开发(包括控件的接受参数 、控件是否已经定型 等等)

**Comment by ChinaIceF** [comment]
#### 感谢！

- 会添加带百分比显示（和自定义显示内容）的进度条，包括线性的和环形进度条
- 文档问题初步打算直接在docstring中实现，并在接下来的开发中逐步完善和丰富，在PyPi上发布后整理并构建在线文档

**Comment by 605037300** [comment]
你有用pyinstaller打包成exe的.spec文件吗，我不知道该咋配置

**Comment by wzl000111** [comment]
如何打包成exe文件呢 报错无法解析gat文件

**Comment by UF4OVER** [comment]
> 如何打包成exe文件呢 报错无法解析gat文件

你可以试着将您的错误之处贴出来，而不是笼统的问这个问题。此外，我或许可以给您打包exe的建议，因为我使用cx-freeze打包成功过EXE文件

**Comment by wzl000111** [comment]
我使用的打包方式为pyinstaller 这是我的报错信息 但是我通过命令行或pycharm都可以启动我的项目并且没有问题 打包后启动exe时先报错找不到我自定义的py文件 在我进行修改后可以找到自定义的py文件 之后又报错无法解析dat文件 报错信息如下：Traceback (most recent call last):
  File "start.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "login.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "siui\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "siui\components\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "siui\components\option_card\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "siui\components\option_card\option_card.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "siui\components\option_card\abstracts\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "siui\components\option_card\abstracts\option_card.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "siui\components\widgets\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "siui\components\widgets\abstracts\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "siui\components\widgets\abstracts\button.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "siui\components\widgets\abstracts\widget.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "siui\core\__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "siui\core\globals.py", line 10, in <module>
  File "siui\core\globals.py", line 25, in SiliconUIGlobal
  File "siui\gui\icons\parser.py", line 21, in __init__
  File "siui\gui\icons\parser.py", line 34, in reload_internals
  File "siui\gui\icons\parser.py", line 40, in load_from_file
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 2: invalid start byte
