### ISSUE TITLE
使用 `VS Code` 直接运行 `./examples/Gallery/start.py` 各种报错找不到文件

### ISSUE THREAD

**Issue by H1DDENADM1N** [ChinaIceF/PyQt-SiliconUI#16]
我是这样成功把它跑起来的，手动修正相对路径，不知道标准不，但能用：

![A731PDVAW51)F5 XFZ{~2TH](https://github.com/ChinaIceF/PyQt-SiliconUI/assets/65646535/542bf598-12d9-487c-8d92-ffe9e26ff23f)

QQ 群友反馈 `PyCharm` 无须改动可以直接运行：

![图片](https://github.com/ChinaIceF/PyQt-SiliconUI/assets/65646535/d2902619-d849-43e3-ac14-eb2942b14251)

但是，还是希望您可以照顾下 `VS Code` 用户，规范相对路径 或 绝对路径。

我的环境：

```powershell
┏[user0][main]
┖[~\Documents\PyQt-SiliconUI]> pdm list --tree
numpy 2.0.0 [ required: >=2.0.0 ]
pyqt5 5.15.10 [ required: >=5.15.10 ]
├── pyqt5-qt5 5.15.2 [ required: >=5.15.2 ]
└── pyqt5-sip 12.13.0 [ required: <13,>=12.13 ]
setuptools 70.1.1 [ required: >=70.1.1 ]
┏[user0][main]
┖[~\Documents\PyQt-SiliconUI]> pdm info && pdm info --env
PDM version:
  2.16.1    
Python Interpreter:
  C:\Users\user0\Documents\PyQt-SiliconUI\.venv\Scripts\python.exe (3.12)
Project Root:
  C:/Users/user0/Documents/PyQt-SiliconUI
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.4",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.12.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "win32"
}
```

**Comment by ChinaIceF** [comment]
是的，应该修改为absolute import，我会在下一个push里规范所有模块的import，感谢提出vscode中的问题

**Comment by ChinaIceF** [comment]
但按理来说不应该会影响icons，updatelogs这些文件夹的读取（如果工作目录是gallery），这可能需要进一步检查？🤔

**Comment by H1DDENADM1N** [comment]
> 但按理来说不应该会影响icons，updatelogs这些文件夹的读取（如果工作目录是gallery），这可能需要进一步检查？🤔

👍你是对的，先运行 `cd examples\Gallery` 可以省很多修改。

![图片](https://github.com/ChinaIceF/PyQt-SiliconUI/assets/65646535/02616ab5-49bb-4d55-889c-912065db67e0)


```powershell
┏[user0][main][xERROR]
┖[~\Documents\PyQt-SiliconUI]> cd examples\Gallery
┏[user0][main]
┖[~\Documents\PyQt-SiliconUI\examples\Gallery]> & c:/Users/user0/Documents/PyQt-SiliconUI/.venv/Scripts/python.exe c:/Users/user0/Documents/PyQt-SiliconUI/examples/Gallery/start.py
当前工作目录 c:/Users/user0/Documents/PyQt-SiliconUI/examples/Gallery/start.py
Traceback (most recent call last):
  File "c:\Users\user0\Documents\PyQt-SiliconUI\examples\Gallery\start.py", line 6, in <module>
    import ui as ui
  File "c:\Users\user0\Documents\PyQt-SiliconUI\examples\Gallery\ui.py", line 19, in <module>
    import components as Components
  File "c:\Users\user0\Documents\PyQt-SiliconUI\examples\Gallery\components\__init__.py", line 3, in <module>
    from . import Glaze
  File "c:\Users\user0\Documents\PyQt-SiliconUI\examples\Gallery\components\Glaze.py", line 16, in <module>
    from .sub_example_A import *
  File "c:\Users\user0\Documents\PyQt-SiliconUI\examples\Gallery\components\sub_example_A.py", line 17, in <module>
    class SubInterface_A(SiliconUI.SiOverlay.SubInterface):
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'SiOverlay' has no attribute 'SubInterface'. Did you mean: 'setInterface'?
┏[user0][main][xERROR]
┖[~\Documents\PyQt-SiliconUI\examples\Gallery]> & c:/Users/user0/Documents/PyQt-SiliconUI/.venv/Scripts/python.exe c:/Users/user0/Documents/PyQt-SiliconUI/examples/Gallery/start.py
当前工作目录 c:/Users/user0/Documents/PyQt-SiliconUI/examples/Gallery/start.py
SiOverlay 重设大小出错
```

**Comment by H1DDENADM1N** [comment]
我写了个批处理 `run_Silicon_Gallery.bat`

```bat
@echo off
cd /d %~dp0
cd examples\Gallery
%~dp0\.venv\Scripts\python.exe start.py
pause
```

![图片](https://github.com/ChinaIceF/PyQt-SiliconUI/assets/65646535/624c72a4-270a-4270-9205-f1049fe49ba8)

**Comment by H1DDENADM1N** [comment]
> 试了一下还是报错

`xcopy /s /e /i /y /q %~dp0\SiliconUI %~dp0\.venv\Lib\site-packages\SiliconUI`

![图片](https://github.com/ChinaIceF/PyQt-SiliconUI/assets/65646535/784432de-3bde-42f2-a84d-c67d62a1675f)
