### ISSUE TITLE
运行报错找不到deteutil

### ISSUE THREAD

**Issue by hellojingbo** [ChinaIceF/PyQt-SiliconUI#174]
python版本 python3.11
IDE pycharm 2023.2.5
平台 Windows 10

cmd: python start.py

output:

已将环境变量 QT_SCALE_FACTOR 设为 1.0  (来源: Windows API)
Traceback (most recent call last):
  File "E:\Projects\PyQt-SiliconUI\examples\Gallery for siui\start.py", line 6, in <module>
    from ui import MySiliconApp
  File "E:\Projects\PyQt-SiliconUI\examples\Gallery for siui\ui.py", line 10, in <module>
    from components.page_widgets import ExampleWidgets
  File "E:\Projects\PyQt-SiliconUI\examples\Gallery for siui\components\page_widgets\__init__.py", line 1, in <module>
    from .page_widgets import ExampleWidgets
  File "E:\Projects\PyQt-SiliconUI\examples\Gallery for siui\components\page_widgets\page_widgets.py", line 41, in <module>
    from siui.components.widgets.timedate import SiCalenderView, SiTimePicker, SiTimeSpanPicker
  File "E:\Projects\PyQt-SiliconUI\siui\components\widgets\timedate.py", line 5, in <module>
    from dateutil.relativedelta import relativedelta
ModuleNotFoundError: No module named 'dateutil'

**Comment by ChinaIceF** [comment]
应该是因为dependencies里忘了写新加的依赖了，我去修改一下，你可以直接在pycharm里安装一下这个库

**Comment by ChinaIceF** [comment]
feel free to reopen this issue
