### ISSUE TITLE
[兼容性问题] 在python3.10及以上版本 dataclass 的处理方式问题

### ISSUE THREAD

**Issue by wang-zhuo996** [ChinaIceF/PyQt-SiliconUI#203]
在python 3.10及以上版本，直接使用QColor 会导致出现ValueError 运行失败  
![image](https://github.com/user-attachments/assets/b532f549-a5e8-41a8-a888-9fa6cbab20f2)
![image](https://github.com/user-attachments/assets/012c685b-c305-4f1a-8228-170e61c1187d)

**Comment by ChinaIceF** [comment]
请提供报错信息

**Comment by wang-zhuo996** [comment]
> 请提供报错信息  
```
Traceback (most recent call last):
  File "e:\_Project\PyQt-SiliconUI\examples\Gallery for siui\start.py", line 6, in <module>
    from ui import MySiliconApp
  File "e:\_Project\PyQt-SiliconUI\examples\Gallery for siui\ui.py", line 10, in <module>
    from components.page_refactor import RefactoredWidgets
  File "e:\_Project\PyQt-SiliconUI\examples\Gallery for siui\components\page_refactor\__init__.py", line 1, in <module>
    from .page_refactor import RefactoredWidgets
  File "e:\_Project\PyQt-SiliconUI\examples\Gallery for siui\components\page_refactor\page_refactor.py", line 8, in <module>
    from siui.components.button import SiPushButtonRefactor, SiProgressPushButton, SiLongPressButtonRefactor, SiFlatButton, \
  File "C:\Users\4070TiSpuer\.pyenv\pyenv-win\versions\3.12.7\Lib\site-packages\pyqt_siliconui-1.0.1-py3.12.egg\siui\components\button.py", line 798, in <module>
    @dataclass
     ^^^^^^^^^
  File "%USERPROFILE%\.pyenv\pyenv-win\versions\3.12.7\Lib\dataclasses.py", line 1275, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "%USERPROFILE%\.pyenv\pyenv-win\versions\3.12.7\Lib\dataclasses.py", line 1265, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "%USERPROFILE%\.pyenv\pyenv-win\versions\3.12.7\Lib\dataclasses.py", line 994, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "%USERPROFILE%\.pyenv\pyenv-win\versions\3.12.7\Lib\dataclasses.py", line 852, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'PyQt5.QtGui.QColor'> for field background_color_starting is not allowed: use default_factory
```
button.py 文件还有几处使用dataclass装饰器的类有类似错误  
`SwitchStyleData` `RadioButtonStyleData`   
还有一个存在于 文件 `slider_.py` 的 类 `CoordinatePickerStyleData` 里

**Comment by rainzee** [comment]
后续应该彻底避免直接构造 QColor 而是使用元数据

**Comment by ChaXxl** [comment]
Python 3.12 同样的报错

**Comment by ChaXxl** [comment]
将所有在 dataclass 里面涉及 QColor 的代码改成这样就行了：

~~~python
from dataclasses import dataclass, field

...

class RadioButtonStyleData(QObject):

    STYLE_TYPES = ["Button"]

    # text_color = QColor("#D1CBD4")
    # description_color = QColor("#918497")

    # 替换为 default_factory
    text_color: QColor = field(default_factory=lambda: QColor("#D1CBD4"))
    description_color: QColor = field(default_factory=lambda: QColor("#918497"))

...
~~~

**Comment by OnesoftQwQ** [comment]
我也是，3.12

**Comment by ChinaIceF** [comment]
当前的样式类是为了方便编写样式分发的模块，故暂时取消使用dataclass，如果问题仍然出现，请Reopen这个issue，谢谢。
